build:
    environment:
        hosts:
            audith.basis: '127.0.0.1'
    dependencies:
        before:
            - sudo apt-get install -y -qq sendmail
            - sudo npm install -g gulp
    project-setup:
        before:
            - mysql -uroot -e 'CREATE DATABASE basis'
        override:
            - php artisan migrate --force --no-interaction
    tests:
        override:
            -
                command: './vendor/bin/phpunit'
                coverage:
                    file: './storage/coverage/coverage.xml'
                    format: 'php-clover'
filter:
    excluded_paths: [vendor/*, tests/*]
tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
