build:
    environment:
        php: '5.4.28'
        node: '0.11.13'
        hosts:
            basis.audith.org: '127.0.0.1'
    dependencies:
        before:
            - cp .env.example .env
            - sudo apt-get install -y -qq sendmail
        override:
            - node -v
            - npm -v
            - npm install -g npm@latest
            - npm install -g gulp bower
            - composer install --no-interaction
    project-setup:
        before:
            - mysql -uroot -e 'CREATE DATABASE basis'
        override:
            - php artisan migrate --force --no-interaction
            - bower install
            -
                command: 'gulp'
                only_if: 'npm install'
    tests:
        override:
            -
                command: './vendor/bin/phpunit'
                coverage:
                    file: './storage/coverage/coverage.xml'
                    format: 'php-clover'
filter:
    excluded_paths: [vendor/*, tests/*]
tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
