mysql56:
  image: mysql:5.6
  environment:
    - MYSQL_DATABASE=basis
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
redis:
  image: redis
hhvmAsFpm:
  image: audithsoftworks/basis:hhvm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - redis
nginxForHhvm:
  image: audithsoftworks/basis:nginx
  volumes:
    - ./storage/build/configs/nginxForHhvm.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/home/basis
  working_dir: /home/basis
  links:
    - hhvmAsFpm
hhvmAsCli:
  image: audithsoftworks/basis:hhvm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - redis
    - nginxForHhvm
  stdin_open: true
