mysql56:
  image: mysql:5.6
  environment:
    - MYSQL_DATABASE=basis
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
postgres94:
  image: postgres:9.4
redis:
  image: redis
phpFpm56:
  image: audithsoftworks/basis:php_5.6-fpm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - postgres94
    - redis
  environment:
    XDEBUG_CONFIG: remote_host=192.168.1.33
nginxForPhpFpm56:
  image: audithsoftworks/basis:nginx
  volumes:
    - ./storage/build/configs/nginxForPhpFpm56.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/home/basis
  working_dir: /home/basis
  links:
    - phpFpm56
php56:
  image: audithsoftworks/basis:php_5.6
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - postgres94
    - redis
    - nginxForPhpFpm56
  environment:
    XDEBUG_CONFIG: remote_host=192.168.1.33
  stdin_open: true
