mysql56:
  image: mysql:5.6
  environment:
    - MYSQL_DATABASE=basis
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
postgres94:
  image: postgres:9.4
redis:
  image: redis
phpFpm55:
  image: audithsoftworks/basis:php_5.5-fpm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - postgres94
    - redis
nginxForPhpFpm55:
  image: audithsoftworks/basis:nginx
  volumes:
    - ./storage/build/configs/nginxForPhpFpm55.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/home/basis
  working_dir: /home/basis
  links:
    - phpFpm55
php55:
  image: audithsoftworks/basis:php_5.5
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mysql56
    - postgres94
    - redis
    - nginxForPhpFpm55
  stdin_open: true
