mariadb10:
  image: mariadb:10.1
  environment:
    - MYSQL_DATABASE=basis
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
postgres:
  image: postgres:9.6
  environment:
    - POSTGRES_DB=basis
    - POSTGRES_PASSWORD=
redis:
  image: redis
phpFpm:
  image: audithsoftworks/basis:php_5.6-fpm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mariadb10
    - postgres
    - redis
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
nginx:
  image: audithsoftworks/basis:nginx
  volumes:
    - ./storage/build/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/home/basis
  working_dir: /home/basis
  links:
    - phpFpm
phpCli:
  image: audithsoftworks/basis:php_5.6
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mariadb10
    - postgres
    - redis
    - nginx
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
  stdin_open: true
