mariadb10:
  image: mariadb:10.1
  environment:
    - MYSQL_DATABASE=basis
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
redis:
  image: redis
phpFpm:
  image: audithsoftworks/basis:hhvm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mariadb10
    - redis
nginx:
  image: audithsoftworks/basis:nginx
  volumes:
    - ./storage/build/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/home/basis
  working_dir: /home/basis
  links:
    - phpFpm
phpCli:
  image: audithsoftworks/basis:hhvm
  volumes:
    - .:/home/basis
  working_dir: /home/basis
  links:
    - mariadb10
    - redis
    - nginx
  stdin_open: true
